version: "3.7"

services:
  recipe-app:
    container_name: recipe-app
    build:
      context: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=recipe-db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - recipe-db

  recipe-db:
    container_name: recipe-db
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres